name: ChromaticQA

on:
  push:

jobs:
  visual_regression:
    runs-on: ubuntu-latest

    steps:
    - name: Variables
      run: |
        echo github '${{ toJson(github) }}'
        echo job '${{ toJson(job) }}'
        echo job '${{ toJson(steps) }}'
        echo job '${{ toJson(runner) }}'
        echo job '${{ toJson(strategy) }}'
        echo job '${{ toJson(matrix) }}'
    # - uses: actions/checkout@v1
    # - uses: actions/setup-node@v1
    #   with:
    #     node-version: 10.x
    # - name: Install Packages
    #   run: yarn install
    # - name: ChromaticQA
    #   run: yarn chromatic
    #   env:
    #     CI: true
    #     CHROMATIC_APP_CODE: ${{ secrets.CHROMATIC_APP_CODE }}
