name: ChromaticQA

on:
  push:

jobs:
  visual_regression:
    runs-on: ubuntu-latest

    steps:
      name: Variables
      run: |
        echo event_name ${{ github.event_name }}
        echo sha ${{ github.sha }}
        echo ref ${{ github.ref }}
        echo head_ref ${{ github.head_ref }}
        echo base_ref ${{ github.base_ref}}
        echo event ${{ toJson(github.event) }}
        echo job ${{ toJson(github.job) }}
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install Packages
      run: yarn install
    - name: ChromaticQA
      run: yarn chromatic
      env:
        CI: true
        CHROMATIC_APP_CODE: ${{ secrets.CHROMATIC_APP_CODE }}
