name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: yarn install --production=false
    - name: Linting
      run: yarn lint
    - name: Build
      run: yarn build
    - name: Unit tests
      run: yarn test
    - name: Integration tests
      run: yarn cypress run --record --key ${{ secrets.CYPRESS_KEY }}
      
